export const STRINGS = {
  app: {
    title: 'DJ APP TURBO 2000',
    masterTransport: 'Master Transport',
    play: 'PLAY',
    playing: 'PLAYING',
  },
  globalControls: {
    save: 'SAVE',
    load: 'LOAD',
    customSounds: 'CUSTOM SOUNDS',
  },
  topBar: {
    saveSet: 'SAVE SET',
    resetSet: 'RESET',
  },
  mixLibrary: {
    newMix: 'NEW MIX',
    loadMix: 'Load mix',
    unsavedMix: 'UNTITLED',
    saveUnsavedMix: 'Save mix',
  },
  mixerHeader: {
    play: 'PLAY',
    stop: 'STOP',
    reset: 'RESET',
    save: 'SAVE',
    saveNew: 'SAVE NEW',
    sounds: 'SOUNDS',
    bpm: 'BPM',
    lockedBySet: 'Mixer is locked while set is playing',
  },
  setSection: {
    playSet: 'PLAY SET',
    stopSet: 'STOP SET',
    newSet: 'NEW',
    saveSet: 'SAVE',
    locked: 'Set is playing — mixer locked',
  },
  trackGrid: {
    drums: 'DRUMS',
    arp: 'ARP',
    bass: 'BASS',
    keys: 'KEYS',
    pad: 'PAD',
    custom: 'CUSTOM',
  },
  trackCard: {
    removeFromMix: 'Remove from mix',
    addToMix: 'Add to mix',
    stopPreview: 'Stop preview',
    preview: 'Preview',
    editTrack: 'Edit track',
    renameTrack: 'Rename track',
    deleteTrack: 'Delete track',
    removeFromFavourites: 'Remove from favourites',
    addToFavourites: 'Add to favourites',
  },
  trackEditModal: {
    title: 'EDIT TRACK',
    preview: 'Preview',
    stopPreview: 'Stop preview',
    levels: 'LEVELS',
    vol: 'VOL',
    speed: 'SPEED',
    eq: 'EQ',
    low: 'LOW',
    mid: 'MID',
    high: 'HIGH',
    fxSends: 'FX SENDS',
    reverb: 'REVERB',
    delay: 'DELAY',
    nameNewPreset: 'NAME NEW PRESET',
    renameLabel: 'NEW NAME',
    presetNamePlaceholder: 'Enter preset name…',
    save: 'Save',
    saveNew: 'Save new',
    confirm: 'Confirm',
    back: 'Back',
    cancel: 'Cancel',
    overwritePresetTooltip: 'Overwrite this preset with current settings',
    saveToTrackTooltip: 'Save current settings to this track',
    saveAsNewTooltip: 'Save as a new preset — original track stays unchanged',
    discardChanges: 'Discard changes',
    resetToDefault: 'Reset to defaults',
  },
  saveLoadManager: {
    saveMixTitle: 'Save mix',
    loadMixTitle: 'Load mix',
    mixNameLabel: 'Mix name',
    defaultMixName: '',
    noSavedMixes: 'No saved mixes yet.',
    savesInfo: 'Stores selected tracks, volume, speed and global tempo.',
    close: 'Close',
    load: 'Load',
    save: 'Save',
    cancel: 'Cancel',
  },
  customSoundsDialog: {
    title: 'Custom Sounds',
    uploadSound: 'Upload sound',
    noCustomSounds: 'No custom sounds stored yet.',
    renameSound: 'Rename sound',
    trimSound: 'Trim sound',
    deleteSound: 'Delete sound',
  },
  soundTrimDialog: {
    title: 'Trim sound',
    selectionHint: 'Drag the handles to keep only the selected part.',
    play: 'Play selection',
    stop: 'Stop',
    loading: 'Loading…',
    start: 'Start',
    end: 'End',
    length: 'Length',
    save: 'Save',
    cancel: 'Cancel',
  },
  confirmDialog: {
    deleteTitle: 'CONFIRM DELETE',
    cancel: 'Cancel',
    confirm: 'Delete',
    deleteTrack: 'Delete this track permanently? This cannot be undone.',
    deleteSound:
      'Delete this custom sound permanently? Any tracks using it will be removed. This cannot be undone.',
    deleteMix: 'Delete this mix permanently? This cannot be undone.',
    deleteSet: 'Delete this set permanently? This cannot be undone.',
  },
  renameDialog: {
    renameTrackTitle: 'RENAME TRACK',
    renameSoundTitle: 'RENAME SOUND',
    renameSetTitle: 'RENAME SET',
    placeholder: 'Enter new name…',
    save: 'Save',
    cancel: 'Cancel',
  },
  unsavedMixDialog: {
    title: 'UNSAVED CHANGES',
    message:
      'The current mix has unsaved changes. Switching will discard them. Save first?',
    save: 'Save',
    saveNew: 'Save new',
    discard: 'Discard & switch',
    cancel: 'Cancel',
  },
  mixEditDialog: {
    createTitle: 'SAVE MIX',
    editTitle: 'EDIT MIX',
    namePlaceholder: 'Mix name…',
    colorLabel: 'COLOR',
    clearColor: 'No color',
    save: 'Save',
    delete: 'Delete',
    cancel: 'Cancel',
  },
  globalTempoPanel: {
    label: 'Global tempo',
    bpm: 'BPM',
  },
  set: {
    tabMixer: 'MIXER',
    tabSet: 'SET',
    mixLibrary: 'MIX LIBRARY',
    noMixes: 'No saved mixes yet.\nSave a mix in the Mixer tab first.',
    addToTimeline: 'Add to set',
    editMix: 'Edit mix',
    duplicateMix: 'Duplicate mix',
    setNamePlaceholder: 'Set name…',
    newSet: 'NEW SET',
    totalDuration: 'Total',
    minutes: 'min',
    noSlots: 'Add mixes from the library to build your set',
    removeSlot: 'Remove',
    duplicateSlot: 'Duplicate',
    savedSets: 'SAVED SETS',
    noSets: 'No saved sets yet.',
    loadSet: 'Load',
    deleteSet: 'Delete',
    renameSet: 'Rename set',
    transitionType: 'Transition',
    transitionCut: 'Cut',
    transitionFade: 'Fade',
    transitionCrossfade: 'Crossfade',
    setDefaultTransition: 'Default transition',
    seconds: 's',
    exportAudio: 'Export set as audio',
  },
  session: {
    save: 'Save session',
    load: 'Load session',
    new: 'New session',
    unsaved: 'Unsaved changes',
    saved: 'All changes saved',
    unsavedTitle: 'UNSAVED CHANGES',
    loadMessage:
      'Loading a session replaces the current one. Unsaved changes will be lost. Continue?',
    newMessage:
      'Starting a new session clears all mixes, sets, sounds and track edits. Unsaved changes will be lost. Continue?',
    loadConfirm: 'Load',
    newConfirm: 'New session',
    cancel: 'Cancel',
    loadFailed: 'Could not load this session file.',
  },
  setExport: {
    exportingTitle: 'EXPORTING SET',
    exportingMessage:
      'Recording the set in real time. This takes as long as the set itself — keep the app open until it finishes.',
    cancel: 'Cancel',
  },
  tutorial: {
    /** Tooltip on the top-bar button that starts the guided tour. */
    open: 'Show tutorial',
    /** Footer navigation buttons and progress. */
    back: 'Back',
    next: 'Next',
    finish: 'Finish',
    close: 'Close tutorial',
    /** e.g. "Step 2 / 6" — rendered with {@link stepOf}. */
    stepLabel: 'Step',
    stepSeparator: '/',
    /** Hint line shown in the popup footer. */
    keyboardHint: 'Enter / → next · ← back · Esc close',
    intro: {
      title: 'WELCOME TO DJ APP TURBO 2000',
      body: 'Take a quick tour of the app. Use Enter or the arrow keys to move between steps, and Esc to leave the tour at any time.',
    },
    mixLibrary: {
      title: 'MIX LIBRARY',
      body: 'Your saved mixes live here. Load one into the mixer, add it straight to a set, or create a brand-new mix to start from scratch.',
    },
    track: {
      title: 'TRACKS',
      body: 'Each sound is a track. Tick it to add it to the mix. Hover a track to reveal its controls: preview it, mark it as a favourite, or open the editor to tweak volume, speed, EQ and effects.',
    },
    trackGrid: {
      title: 'THE MIXER',
      body: 'Tracks are grouped by category — drums, arp, bass, keys, pad and your own custom sounds. Combine them to build a mix, then save it to the library.',
    },
    setSection: {
      title: 'SET BUILDER',
      body: 'Arrange your saved mixes on the timeline to build a full DJ set. Set the duration of each mix and the transition between them, then play or export the whole set.',
    },
    session: {
      title: 'YOUR SESSION',
      body: 'Everything — mixes, sets, sounds and edits — is your session. Save it to a file, load it back later, or start fresh from here.',
    },
    outro: {
      title: 'YOU ARE READY',
      body: 'That is the tour. Press the info button in the top bar whenever you want to see it again. Have fun mixing!',
    },
  },
} as const;
