export const STRINGS = {
  app: {
    title: 'NEON MIXER',
    masterTransport: 'Master Transport',
    play: 'PLAY',
    playing: 'PLAYING',
  },
  globalControls: {
    save: 'SAVE',
    load: 'LOAD',
    customSounds: 'CUSTOM SOUNDS',
  },
  trackGrid: {
    drums: 'DRUMS',
    arp: 'ARP',
    bass: 'BASS',
    keys: 'KEYS',
    pad: 'PAD',
    custom: 'CUSTOM',
  },
  trackCard: {
    removeFromMix: 'Remove from mix',
    addToMix: 'Add to mix',
    stopPreview: 'Stop preview',
    preview: 'Preview',
    editTrack: 'Edit track',
    removeFromFavourites: 'Remove from favourites',
    addToFavourites: 'Add to favourites',
  },
  trackEditModal: {
    title: 'EDIT TRACK',
    levels: 'LEVELS',
    vol: 'VOL',
    speed: 'SPEED',
    eq: 'EQ',
    low: 'LOW',
    mid: 'MID',
    high: 'HIGH',
    fxSends: 'FX SENDS',
    reverb: 'REVERB',
    delay: 'DELAY',
    nameNewPreset: 'NAME NEW PRESET',
    presetNamePlaceholder: 'Enter preset name…',
    save: 'Save',
    saveNew: 'Save new',
    confirm: 'Confirm',
    back: 'Back',
    cancel: 'Cancel',
    overwritePresetTooltip: 'Overwrite this preset with current settings',
    saveToTrackTooltip: 'Save current settings to this track',
    saveAsNewTooltip: 'Save as a new preset — original track stays unchanged',
    discardChanges: 'Discard changes',
  },
  saveLoadManager: {
    saveMixTitle: 'Save mix',
    loadMixTitle: 'Load mix',
    mixNameLabel: 'Mix name',
    defaultMixName: 'Neon Session',
    noSavedMixes: 'No saved mixes yet.',
    savesInfo: 'Stores selected tracks, volume, speed and global tempo.',
    close: 'Close',
    load: 'Load',
    save: 'Save',
    cancel: 'Cancel',
  },
  customSoundsDialog: {
    title: 'Custom Sounds',
    uploadSound: 'Upload sound',
    noCustomSounds: 'No custom sounds stored yet.',
  },
  globalTempoPanel: {
    label: 'Global tempo',
    bpm: 'BPM',
  },
} as const;
